global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
  - job_name: "hdfs-exporter"
    static_configs:
      - targets: ["hdfs-exporter:9105"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
