POSTGRES_HOST: postgres
POSTGRES_PORT: 5432
POSTGRES_DB: weatherdb
POSTGRES_USER: user
POSTGRES_PASSWORD: password

HADOOP_NAMENODE_HOST: namenode
HADOOP_NAMENODE_PORT: 9870
HADOOP_JMX_URI: "http://namenode:9870/jmx"