OPENWEATHER_API_KEY: "34a09902da14d98cce424fbfc4355d75"

TOPIC_NAME: "weather-api"
GROUP_ID: "weather-consumer-group"
BOOTSTRAP_SERVERS: "kafka:9092"

PG_HOST: "postgres"
PG_PORT: "5432"
PG_DB: "weatherdb"
PG_USER: "user"
PG_PASSWORD: "password"
POSTGRES_USER: "user"
POSTGRES_PASSWORD: "password"