OPENWEATHER_API_KEY: "34a09902da14d98cce424fbfc4355d75"
BOOTSTRAP_SERVERS: "kafka:9092"
TOPIC_NAME: "weather-api"
CITY: "Paris"

HDFS_BASE_PATH: "/hadoop/dfs/name"
HDFS_USER: "hdfs"
HDFS_URL: "http://namenode:9870/"

POSTGRES_HOST: "postgres"
POSTGRES_DB: "weatherdb"
POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: "postgres"
POSTGRES_PORT: "5432"