OPENWEATHER_API_KEY: 34a09902da14d98cce424fbfc4355d75

TOPIC_NAME: weather-api
GROUP_ID: weather-consumer-group
BOOTSTRAP_SERVERS: kafka:9092

POSTGRES_HOST: postgres
POSTGRES_PORT: 5432
POSTGRES_DB: weatherdb
POSTGRES_USER: user
POSTGRES_PASSWORD: password
