version: "3.8"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    env_file:
      - .env
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_namenode_rpc_address_namenode=namenode:8020
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - INIT_DFS_PERMISSIONS=no
    ports:
      - "9870:9870"
      - "8020:8020"
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - infra-kafka

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    env_file:
      - .env
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - SERVICE_PRECONDITION=namenode:8020
    volumes:
      - datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - infra-kafka

  pull-hdfs:
    build: ./hadoop-pull
    container_name: pull-hdfs
    env_file:
      - .env
    depends_on:
      - namenode
    networks:
      - infra-kafka

networks:
  infra-kafka:
    external: true

volumes:
  namenode:
  datanode:
